import Head from "next/head";
import Image from "next/image";
import Nav from "./sections/nav";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-6 py-5 h-screen w-full">
        <header className="h-1/4 bg-bg -mx-6 px-6 py-5 -my-5 border-b-2">
          {/* nav bar */}
          <Nav />
        </header>
      </main>
    </div>
  );
}
