import Head from "next/head";
import Image from "next/image";
import Cards from "./sections/Cards";
import Nav from "./sections/nav";
import Status from "./sections/Status";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-6 py-5 h-screen w-full flex flex-col gap-2">
        <header className="h-1/4 bg-bg -ml-6 -mr-6 px-6 py-5 -my-5 border-b-2 relative">
          {/* nav bar */}
          <Nav />
          <Cards />
        </header>{" "}
        {/*status section */}
        <Status />
      </main>
    </div>
  );
}
